# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Compile Solution (Debug)

on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Space Engineers cache
        uses: actions/cache@v3.2.5
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: se\
          # An explicit key for restoring and saving the cache
          key: seds
          
      - name: NuGet cache
        uses: actions/cache@v3.2.5
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: packages\
          # An explicit key for restoring and saving the cache
          key: solution_packages

      # Install SteamCMD
      - name: Setup SteamCMD
        uses: CyberAndrii/setup-steamcmd@v1.1.5

        # Install Space Engineers Dedicated Server
      - name: Install Space Engineers
        run: steamcmd +force_install_dir $env:GITHUB_WORKSPACE\se +login anonymous +app_update 298740 +quit
        shell: powershell

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Solution
        run: |
          cmd /c mklink /J Bin64 se\DedicatedServer64
          msbuild -t:restore -p:RestorePackagesConfig=true ProjectEclipse.SSGI.sln
          msbuild -t:Build -p:OutputPath=..\build,Configuration=Debug,Platform=x64,TargetFrameworkVersion=v4.8 ProjectEclipse.SSGI/ProjectEclipse.SSGI.csproj

      - name: Copy Shaders to Output
        run: Copy-Item -Path "ProjectEclipse.SSGI/Shaders" -Destination "build" -Recurse

      #- name: Upload a Build Artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: compiled_plugin
      #    path: build/
      #    if-no-files-found: warn
      #    retention-days: 0

      - name: Get Current Date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1.4.0
        with:
          format: "YYYY-MM-DD"

      - name: Create ZIP Archive
        run: Compress-Archive -Path build/* -Destination  ssgi-plugin.zip

      - name: Create Archive Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: "${{ steps.date.outputs.time }}"
          #name: ""
          body: |
            ###### Released using GitHub Actions - [${{ github.workflow }} workflow #${{ github.run_number }}](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})
          artifacts: "ssgi-plugin.zip"
          allowUpdates: "true"
          artifactErrorsFailBuild: "true"
          removeArtifacts: "true"
          replacesArtifacts: "true"
